---
galaxy_info:
  author: Your Name
  description: Web service role for Nginx (Linux) and IIS (Windows)
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions: [7, 8]
    - name: Ubuntu
      versions: [18.04, 20.04]
dependencies: []
